[package]
name = "ds-transcriber"
version = "0.1.0"
authors = ["Kawaki-san"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.3"
deepspeech = "0.9.0"
nnnoiseless = "0.3.2"
